db:
  image: kartoza/postgis:9.4-2.1
  restart: always
  environment:
    - POSTGRES_USER=docker
    - POSTGRES_PASSWORD=docker
  volumes:
    - ./postgresql/data:/var/lib/postgresql/data

uwsgi:
  build: docker
  dockerfile: Dockerfile
  hostname: uwsgi
  environment:
    - DATABASE_NAME=postgres
    - DATABASE_USERNAME=docker
    - DATABASE_PASSWORD=docker
    - DATABASE_HOST=db
    - DJANGO_SETTINGS_MODULE=core.prod_docker
  volumes:
    - ./docker/uwsgi.conf:/uwsgi.conf
    - ../django_project:/home/web/django_project
    - ./static:/home/web/static
    - ./media:/home/web/media
    - ./logs:/var/log/
  links:
    - db:db

web:
  image: nginx
  hostname: nginx
  restart: always
  volumes:
    - ./sites-enabled:/etc/nginx/conf.d:ro
    - ./static:/home/web/static:ro
    - ./media:/home/web/media:ro
    - ./logs:/var/log/nginx
  links:
    - uwsgi:uwsgi
  ports:
    - "61201:8080"
